### ISSUE TITLE
Error installing NF package

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/NonlinearNormalForm.jl#24]
What I see is:

julia> import Pkg; Pkg.add(path="https://github.com/bmad-sim/NonlinearNormalForm.jl")
     Cloning git-repo `https://github.com/bmad-sim/NonlinearNormalForm.jl`
    Updating git-repo `https://github.com/bmad-sim/NonlinearNormalForm.jl`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GTPSA_jll [a4739e29]:
 GTPSA_jll [a4739e29] log:
 ├─possible versions are: 1.0.0-1.3.0 or uninstalled
 └─restricted to versions 1.3.1-1 by GTPSA [b27dd330] — no versions left
   └─GTPSA [b27dd330] log:
     ├─possible versions are: 0.6.1 or uninstalled
     ├─restricted to versions 0.5.2-0.5 by NonlinearNormalForm [05e19671] — no versions left
     │ └─NonlinearNormalForm [05e19671] log:
     │   ├─possible versions are: 1.0.0 or uninstalled
     │   └─NonlinearNormalForm [05e19671] is fixed to version 1.0.0-DEV
     └─GTPSA [b27dd330] is fixed to version 0.6.1
Stacktrace:
  [1] check_constraints(graph::Pkg.Resolve.Graph)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:998
  [2] Pkg.Resolve.Graph(compat::Dict{…}, compat_weak::Dict{…}, uuid_to_name::Dict{…}, reqs::Dict{…}, fixed::Dict{…}, verbose::Bool, julia_version::VersionNumber)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:345
  [3] deps_graph(env::Pkg.Types.EnvCache, registries::Vector{…}, uuid_to_name::Dict{…}, reqs::Dict{…}, fixed::Dict{…}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:586
  [4] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:406
  [5] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1360
  [6] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, julia_version::VersionNumber, try_all_installed::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1349
  [7] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1370
  [8] add(ctx::Pkg.Types.Context, pkgs::Vector{…}, new_git::Set{…}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1387
  [9] add
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1376 [inlined]
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{…}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::@Kwargs{…})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:278
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:148
 [13] add(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::String, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::@Kwargs{})
    @ Pkg.API ./boot.jl:0
 [14] top-level scope
    @ REPL[1]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia>

**Comment by mattsignorelli** [comment]
For some reason Julia's automerge for the jll got hung https://github.com/JuliaRegistries/General/pull/106713 . I reached out in the Slack and it is fixed now. Try removing NonlinearNormalForm, updating, and adding again

**Comment by mattsignorelli** [comment]
This current GTPSA will corrupt the memory if more than one Descriptor is defined with the same NO but different MOs . Once Laurent fixes it I will update again

**Comment by DavidSagan** [comment]
@mattsignorelli I still get the same error. Note: I do not have a local copy of the repo.

**Comment by DavidSagan** [comment]
I finally removed everything from .julia and was able to install. Go figure.
